# apps/seogeo/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: seogeo-backend-service
  namespace: default
spec:
  selector:
    app: seogeo-backend
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 8080  # Container port
  type: ClusterIP