apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensandbox-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1 — the controller chart
    - repoURL: https://github.com/ObaidDev/OpenSandbox.git
      targetRevision: main
      path: kubernetes/charts/opensandbox-controller
      helm:
        releaseName: opensandbox-controller
        valueFiles:
          - $values/opensandbox/values/controller.yaml

    # Source 2 — your argocd GitOps repo (provides $values)
    - repoURL: https://github.com/ObaidDev/argocd.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default # it does not override the namespace in the controller chart, we should override using this value namespaceOverride :"default"