apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing, avoids rate limits)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: abdellatif.hour.web@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: haproxy
---
# Production issuer — switch to this when staging works correctly
# Update ingress annotation to: cert-manager.io/cluster-issuer: "letsencrypt-prod"
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: abdellatif.hour.web@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: haproxy
