#ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-bufferpost.systrox.com
    secretName: main-ingress-tls      # cert-manager will auto-create this secret
  rules:
  # - host: api-bufferpost.systrox.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: bufferpost-backend-service
  #           port:
  #             number: 80

  - host: api-seogeo.systrox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seogeo-backend-service
            port:
              number: 80

  - host: sandbox.systrox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opensandbox-server
            port:
              number: 80